[package]
name = "HelloWorld"
version = "0.1.0"
authors = ["Mike Donovan <8869801+donovm@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
